language: android

notifications:
  email: false
  
env:
  global:
     - ANDROID_API_LEVEL=26
     - EMULATOR_API_LEVEL=21
     - ANDROID_BUILD_TOOLS_VERSION=27.0.3
    - ADB_INSTALL_TIMEOUT=60
  matrix:
     - ANDROID_TARGET=android-24  ANDROID_ABI=armeabi-v7a

android:
  components:
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    
    # The SDK version used to compile your project
    - $ANDROID_TARGET
    
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-$ANDROID_TARGET

jdk: oraclejdk8

before_install:
    - yes | sdkmanager "platforms;android-26"
    - chmod +x gradlew
    - echo yes | android update sdk --all --filter build-tools-27.0.3 --no-ui --force

# Emulator Management: Create, Start and Wait
before_script:
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-window &
    - android-wait-for-emulator
      
    - adb shell settings put global window_animation_scale 0 &
    - adb shell settings put global transition_animation_scale 0 &
    - adb shell settings put global animator_duration_scale 0 &
    - adb shell input keyevent 82 &
    
licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
    - ./gradlew build connectedAndroidTest --stacktrace