language: android

notifications:
  email: false
  
env:
  global:
   - ANDROID_API_LEVEL=26
   - EMULATOR_API_LEVEL=21
   - ANDROID_BUILD_TOOLS_VERSION=27.0.3
  matrix:
   - ANDROID_TARGET=android-24  ANDROID_ABI=armeabi-v7a

android:
  components:
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    
    # The SDK version used to compile your project
    - $ANDROID_TARGET
    
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-$ANDROID_TARGET

jdk: oraclejdk8

before_install:
  - yes | sdkmanager "platforms;android-26"
  - chmod +x gradlew

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator

script:
  - ./gradlew build connectedAndroidTest --stacktrace